name: text_serializer
description: |-
  [text_serializer]
  A wrapper library for dart.convert.json and yaml/yaml_writer packages.
version: 2025.502.1757
homepage: 
repository: https://github.com/dart-pkg/text_serializer
topics:
  - json
  - yaml
  - config-format
environment:
  sdk: ^3.7.2
platforms:
  android: 
  ios: 
  linux: 
  macos: 
  web: 
  windows: 
dependencies:
  yaml_io: ^2025.502.1751
dev_dependencies:
  test: ^1.25.15
  lints: ^5.1.1
