name: text_serializer
description: |-
  [text_serializer]
  A wrapper library for dart.convert.json and yaml/yaml_writer packages.
version: 2025.428.923
homepage: 
repository: https://github.com/dart-pkg/text_serializer
topics:
  - json
  - yaml
  - config-format
environment:
  sdk: ^3.7.2
dependencies:
  yaml: ^3.1.3
  yaml_magic: ^1.0.6
  yaml_writer: ^2.1.0
dev_dependencies:
  test: ^1.25.15
  lints: ^5.1.1
