name: text_serializer
description: text_serializer package project
version: 2025.421.821
homepage:
repository: https://github.com/dart-pkg/text_serializer

environment:
  sdk: ^3.7.2

dependencies:
  yaml: ^3.1.3
  yaml_writer: ^2.1.0

dev_dependencies:
  test: ^1.25.15
  lints: ^5.1.1
  embed: ^1.4.1
  build_runner: ^2.4.15
